version: '3.3'

services:

  app:
    build:
      context: .
    image: quiz
    ports:
      - "8000:8000"
    volumes:
      - ./quiz:/usr/src/app
    env_file: .env
    command: >
      sh -c 'python manage.py migrate &&
      python manage.py loaddata tests &&
      python manage.py loaddata questions &&
      python manage.py loaddata answers &&
      python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/db
    env_file:
      .env
    ports:
      - "5432:5432"

volumes:
  db-data:
