# Generated by Django 4.1.4 on 2022-12-14 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='checked',
        ),
        migrations.AddField(
            model_name='testset',
            name='users',
            field=models.ManyToManyField(related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
