# Generated by Django 4.1.4 on 2022-12-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_remove_useranswer_test_alter_useranswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='users',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.testset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.usertest'),
            preserve_default=False,
        ),
    ]
