# Generated by Django 4.1.4 on 2022-12-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_testset_users_remove_useranswer_user_usertest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
